"""empty message

Revision ID: 8bd361b24bc2
Revises: d07d04537c2b
Create Date: 2019-04-07 09:21:46.987488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd361b24bc2'
down_revision = 'd07d04537c2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('id_user', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pet', 'user', ['id_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pet', type_='foreignkey')
    op.drop_column('pet', 'id_user')
    # ### end Alembic commands ###
