"""empty message

Revision ID: d07d04537c2b
Revises: ba07b1e1daf0
Create Date: 2019-04-07 09:12:41.436144

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07d04537c2b'
down_revision = 'ba07b1e1daf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('adress', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'adress')
    # ### end Alembic commands ###
