"""empty message

Revision ID: d7394159450d
Revises: 8bd361b24bc2
Create Date: 2019-04-18 17:36:14.483343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7394159450d'
down_revision = '8bd361b24bc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('raza', sa.String(length=20), nullable=True))
    op.drop_constraint('pet_ibfk_1', 'pet', type_='foreignkey')
    op.drop_column('pet', 'new')
    op.drop_column('pet', 'id_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pet', sa.Column('id_user', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('pet', sa.Column('new', mysql.VARCHAR(length=20), nullable=True))
    op.create_foreign_key('pet_ibfk_1', 'pet', 'user', ['id_user'], ['id'])
    op.drop_column('pet', 'raza')
    # ### end Alembic commands ###
