"""empty message

Revision ID: efedc8e2e813
Revises: d7394159450d
Create Date: 2019-04-18 17:40:26.658437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efedc8e2e813'
down_revision = 'd7394159450d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_x__user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_pet', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pet'], ['pet.id'], ),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_x__user')
    # ### end Alembic commands ###
